/*
 * GAPHeader.h
 *
 *  Created on: 2016年12月20日
 *      Author: john
 */

#ifndef GAPHEADER_H_
#define GAPHEADER_H_


#define  GAP_CMD_ALLOW_DEVICE_JOIN 0X01
#define GAP_CMD_NEW_DEVICE_JOIN_NOTIFY 0X02
#define GAP_DELETE_DEVICE 0x03
#define GAP_DELETE_DEVICE_Ret 0x33
//#define GAP_SET_DEVICE_ACK 0x04
//#define GAP_SET_DEVICE_ACK_Ret 0x34
#define GAP_GET_DEVICESLIST 0x05
#define GAP_GET_DEVICESLIST_Ret 0x35

#define GAP_GET_DEVICE_ACK 0x08
#define GAP_GET_DEVICE_ACK_Ret 0x38

#define GAP_SET_DEVICE_ACK 0x09
#define GAP_SET_DEVICE_ACK_Ret 0x39


#define GAP_GET_DEVICE_SUBKEY 0x0A
#define GAP_GET_DEVICE_SUBKEY_Ret 0x3A

#define GAP_GET_DEVICES_INFO 0x06
#define GAP_GET_DEVICES_INFO_Ret 0x36
#define GAP_CONTROL_DEVICE 0x07
#define GAP_CONTROL_DEVICE_Ret 0x37

#define GAP_GET_GATEWAY_STATUE	0x10
#define GAP_GET_GATEWAY_STATUE_Ret 0x40
#define GAP_CONTROL_LAMP 0x11
#define GAP_CONTROL_LAMP_Ret 0x41
#define GAP_OPEN_TMP_SSID 0x12
#define GAP_OPEN_TMP_SSID_Ret 0x42
#define GAP_SET_ONLY_SSID 0x13
#define GAP_SET_ONLY_SSID_Ret 0x43
#define GAP_OPEN_EASYLINK 0x14
#define GAP_OPEN_EASYLINK_Ret 0x44
#define GAP_SET_SYSTEM 0x15

#define GAP_SET_NET_MODE 0x16
#define GAP_SET_NET_MODE_Ret 0x46
#define GAP_SET_UPDATE_URL 0x17
#define GAP_SET_UPDATE_URL_Ret 0x47

#endif /* GAPHEADER_H_ */

